# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Kayleh
subtitle: 'blog | Dreamaker' #标题1 | 标题2
description: 'Dreamaker'
keywords: kayleh,blog,algo,algorithm,cpp,java
author: Kayleh
# 多语言
language: [zh-CN,en]
#avatar: 您的头像链接
avatar: https://cdn.jsdelivr.net/gh/kayleh/cdn/img/2.jpg
#favicon: 您的网站icon
favicon: https://cdn.jsdelivr.net/gh/kayleh/cdn/img/2.jpg



# hexo-generator-i18n
# hexo-generator-i18n 选项（可选，默认使用如下设置）
# i18n:
#   type: [page, post]
#   generator: [index, archive, category, tag]

timezone: ''
# timezone: Asia/Shanghai #中国的时区，不要乱改城市

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# year:month:day/:translate_title.html
url: https://blog.kayleh.top
root: /
# permalink: :year/:month/:day/:title/
# permalink: archives/:title.html
#:translate_title/
permalink: :translate_title/

# permalink: :year:month:day/:translate_title.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stellar
# hexo-theme-octo
# hexo-theme-typography
# volantis
# stellar


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  # - type: git
  #   repository: https://e.coding.net/kayleh/Kayleh.coding.me.git
  #   branch: master
  - type: git
    repo:
      github: git@github.com:Kayleh/Kayleh.github.io.git
      # coding: git@e.coding.net:kayleh/Kayleh.git,master
      # gitee: git@gitee.com:kayleh/kayleh.git
    branch: master
  - type: baidu_url_submitter

baidu_url_submit:
  count: 10               # 提交最新的多少个链接
  host: kayleh.top   # 在百度站长平台中添加的域名
  token: EBlcNcQTTojqoOYR      # 秘钥
  path: baidu_urls.txt   # 文本文档的地址， 新链接会保存在此文本文档里


#插件配置
Plugins:
  - hexo-generator-feed
  - hexo-generator-sitemap
  - hexo-generator-baidu-sitemap
  - hexo-generator-category-enhance
  - hexo-asset-image
  - hexo-prism-plugin
  - hexo-toc
# # rss设置
# feed:
#   type: atom
#   path: atom.xml
#   limit: 20

# #本地搜索配置
# search:
#   path: search.json
#   field: post

#站点地图，seo搜索引擎需要
#sitemap:
#  path: sitemap.xml
#baidusitemap:
#  path: baidusitemap.xml

# # 是否开启字数统计
# #不需要使用，直接设置值为false，或注释掉
# word_count: true


# # 访问优化
# # minifier
# all_minifier: true
# html_minifier:
#   enable: true
#   ignore_error: false
#   exclude:
# css_minifier:
#   enable: true
#   exclude:
#     - '*.min.css'
# js_minifier:
#   enable: false
#   mangle: true
#   output:
#   compress:
#   exclude:
#     - '*.min.js'
# image_minifier:
#   enable: false
#   interlaced: false
#   multipass: false
#   optimizationLevel: 2
#   pngquant: false
#   progressive: false

#看板娘
live2d:
  enable: true
# live2d:
#   enable: true
#   scriptFrom: local
#   pluginRootPath: live2dw/
#   pluginJsPath: lib/
#   pluginModelPath: assets/
#   tagMode: true
#   model:
#     # use: live2d-widget-model-haruto  #选择哪种模型
#     # use: live2d-widget-model-koharu
#     # use: https://gcore.jsdelivr.net/gh/kayleh/cdn/live2d-widget-model-koharu/assets/koharu.model.json

#     use: live2d-widget-model-koharu
#   display: #放置位置和大小
#     position: right
#     width: 112
#     height: 225
#   mobile:
#     show: true #是否在手机端显示

# symbols_count_time:
#   symbols: true #是否统计字数
#   time: true #是否统计阅读时长
#   total_symbols: true #是否统计总字数
#   total_time: true #是否统计总阅读时长


# hexo-neat
# 开关
neat_enable: true
# 压缩 html
neat_html:
  enable: true
  exclude:
    - '**/*.md'
# 压缩 css
neat_css:
  enable: false
  exclude:
    - '**/*.min.css'
# 压缩 js
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'
    - '**/jquery.fancybox.pack.js'
    - '**/index.js'

##---------------------------------------------------------------------------------------------------隐藏
## # 翻译
## # # 修改原链接格式：permalink: :year/:month/:day/:title/
## # permalink: :year:month:day/:translate_title.html
#translate_title:
#  translate_way: google  # google,youdao,baidu_with_appid,baidu_no_appid
#  is_need_proxy: false     # true | false
#  # proxy_url: http://localhost:50018 # Your proxy_url
#  # youdao_api_key: '' # Your youdao_api_key
#  # youdao_keyfrom: xxxx-blog # Your youdao_keyfrom
#  # baidu_appid: '' # Your baidu_appid
#  # baidu_appkey: '' # Your baidu_appkey
#
## # PWA
## # offline config passed to sw-precache.
## offline:
##   maximumFileSizeToCacheInBytes: 10485760 # 缓存的最大文件大小，以字节为单位
##   staticFileGlobs:
##     - public/**/*.{js,html,css,png,jpg,gif,svg,webp,eot,ttf,woff,woff2}
##   # 静态文件合集，如果你的站点使用了例如webp格式的文件，请将文件类型添加进去。
##   stripPrefix: public
##   verbose: true
##   runtimeCaching:
##     # CDNs - should be cacheFirst, since they should be used specific versions so should not change
##     - urlPattern: /* # 如果你需要加载CDN资源，请配置该选项，如果没有，可以不配置。
##       handler: cacheFirst
##       options:
##         origin: https://kayleh.top # 可替换成你的 url
#
## # 数学公式
#kramed:
#  gfm: true
#  pedantic: false
#  sanitize: false
#  tables: true
#  breaks: true
#  smartLists: true
#  smartypants: true
#

#
##hexo-theme-typography
## Generate archive page
#archive_generator:
#  per_page: 0
#
## Generate categories index page and each category page
## category_generator:
##   per_page: 10
##   enable_index_page: true
#
## Generate tags index page and each tag page
#tag_generator:
#  per_page: 10
#  enable_index_page: false
#
## Generator atom feed for you website
#feed:
#  type: atom
#  path: atom.xml
#  limit: 20
#  hub:
#  content:
#  content_limit: 140
#  content_limit_delim: ' '
#
## For syntax highlighting
## prism_plugin:
##   mode: 'preprocess'
##   theme: 'default'
##   line_number: true
#
## offline config passed to sw-precache.
##service_worker:
##  maximumFileSizeToCacheInBytes: 5242880
##  staticFileGlobs:
##    - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
##  stripPrefix: public
##  verbose: true
#service_worker:
#  maximumFileSizeToCacheInBytes: 5242880
#  staticFileGlobs:
#    - public/js/*
#  stripPrefix: public
#  verbose: false
#  runtimeCaching:
#    - urlPattern: /**/*
#      handler: cacheFirst
#      options:
#        origin: blog.kayleh.top
#
#filter_optimize:
#  enable: true
#  # remove static resource query string
#  #   - like `?v=1.0.0`
#  remove_query_string: true
#  # remove the surrounding comments in each of the bundled files
#  remove_comments: true
#  css:
#    enable: true
#    # bundle loaded css file into the one
#    bundle: true
#    # use a script block to load css elements dynamically
#    delivery: true
#    # make specific css content inline into the html page
#    #   - only support the full path
#    #   - default is ['css/main.css']
#    inlines:
#    excludes:
#  js:
#    # bundle loaded js file into the one
#    bundle: true
#    excludes:
#  # set the priority of this plugin,
#  # lower means it will be executed first, default is 10
#  priority: 12
#
#
#
cache: true
#
#import:
#  meta:
#    - <meta name="msapplication-TileColor" content="#ffffff">
#    - <meta name="msapplication-config" content="https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/browserconfig.xml">
#    - <meta name="theme-color" content="#ffffff">
#    - <meta name="google-site-verification" content="LQn0xwjfEU_V6CXCA0qAdwM4qRXtblIbfy5KuzEKaRg" />
#
#  link:
#    - <link rel="apple-touch-icon" sizes="180x180" href="https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/apple-touch-icon.png">
#    - <link rel="icon" type="image/png" sizes="32x32" href="https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/favicon-32x32.png">
#    - <link rel="icon" type="image/png" sizes="16x16" href="https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/favicon-16x16.png">
#    - <link rel="manifest" href="https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/site.webmanifest">
#    - <link rel="mask-icon" href="https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/safari-pinned-tab.svg" color="#5bbad5">
#    - <link rel="shortcut icon" href="https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/favicon.ico">
#  script:
#    # - <script async="" src="https://widget.daovoice.io/widget/38b1c911.js" charset="utf-8"></script>
#    - <script data-ad-client="ca-pub-7457165067653912" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
#    - <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 打赏之后横向 --><ins class="adsbygoogle"style="display:inline-block;width:728px;height:90px"data-ad-client="ca-pub-7457165067653912"data-ad-slot="9837525717"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
#    # - <script>var _hmt = _hmt || [];(function() {var hm = document.createElement("script");hm.src = "https://hm.baidu.com/hm.js?24f5d46da7ff42ae73ccea4ea7114e1b";var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(hm, s);})();</script>
#    - <script>var _hmt = _hmt || [];(function() {var hm = document.createElement("script");hm.src = "https://hm.baidu.com/hm.js?2cd1dc193190f18fed292accb735c684";var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(hm, s);})();</script>
#
##---------------------------------------------------------------------------------------------------

inject:
  head:
    - <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+SC&display=swap" rel="stylesheet">
    # @font-face {
    - <link rel="preconnect" href="https://s1.hdslb.com/" /> - <link rel="stylesheet" href="//s1.hdslb.com/bfs/static/jinkela/long/font/regular.css" media="all" onload="this.media='all'" /> - <link rel="stylesheet" href="//s1.hdslb.com/bfs/static/jinkela/long/font/medium.css" media="all" onload="this.media='all'" />
  script:
    - <script src="//code.tidio.co/dq5klo9ydptaxokj83vcwnusf63dogzr.js" async></script>
    - <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7457165067653912"
     crossorigin="anonymous"></script>

