name: auto deploy

on:
  push:
    branches:
      - dev_hugo  # Set a branch to deploy

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境为最新版 Ubuntu
    name: auto deploy
    steps:
    # 1. 获取源码
    - name: Checkout
      uses: actions/checkout@v3 # 使用 actions/checkout@v3
      with:
        submodules: false  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    # 2. 配置环境
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        # hugo-version: '${{ steps.hugo-version.outputs.HUGO_VERSION }}'
        hugo-version: '0.121.2'
        extended: true

    # 3. 生成静态文件
    - name: Generate Public Files
      run: |
        cd ./hugo_extended_0.121.2_windows-amd64/kayleh.top/
        hugo --minify
        # 配置 SSH
        mkdir -p ~/.ssh && echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa  && ssh-keyscan github.com >> ~/.ssh/known_hosts
        # 配置 Git
        git config --global user.name 'kayleh'
        git config --global user.email 'yaojinqing@kayleh.top'

    # 4. 部署到 GitHub 仓库（可选）
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        external_repository: Kayleh/kayleh.github.io
        publish_branch: master #gh-pages
        publish_dir: ./hugo_extended_0.121.2_windows-amd64/kayleh.top/public
        commit_message: ${{ github.event.head_commit.message }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
#    # 5. 部署到服务器（可选）
#    - name: Deploy to Server
#      uses: easingthemes/ssh-deploy@v3
#      env:
#        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#        ARGS: "-rltgoDzvO --delete"
#        EXCLUDE: ".well-known, .user.ini"
#        SOURCE: public/
#        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
#        REMOTE_USER: ${{ secrets.REMOTE_USER }}
#        TARGET: ${{ secrets.TARGET }}
